{{- $mongoPassword := randAlphaNum 32 }}
{{- $redisPassword := randAlphaNum 32 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ "admin" | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $mongoPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ $redisPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
type: Opaque
data:
  JWT_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  REFRESH_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
stringData:
  MONGODB_URI: "mongodb://admin:{{ $mongoPassword }}@mongodb-service:27017/planner-and-tracker?authSource=admin"
  REDIS_URL: "redis://:{{ $redisPassword }}@redis-service:6379"
  API_URL: "https://{{ .Values.ingress.host }}"
  WEB_URL: "https://{{ .Values.ingress.host }}"
