{{- $mongoPassword := randAlphaNum 32 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ "admin" | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $mongoPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  JWT_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  REFRESH_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
stringData:
  MONGODB_URI: "mongodb://admin:{{ $mongoPassword }}@mongodb-service:27017/planner-and-tracker?authSource=admin"
  API_URL: "https://{{ .Values.ingress.host }}"
