image:
  registry: kyrokrypt
  pullPolicy: Always
  server:
    tag: latest
  client:
    tag: latest

ingress:
  host: pat.timothyw.dev
  ingressClassName: traefik

mongodb:
  port: "30019"
  storage:
    size: "2Gi"
    storageClass: "local-path"